FROM 192.168.200.224:8132/docker-hosted/ubuntu:20.04 AS base
FROM base as build

EXPOSE 8081:80

RUN apt update
#RUN apt install nginx  nano -y
RUN apt install python2 -y
RUN apt update && apt install software-properties-common -y
RUN apt install curl -y

COPY ./nginx_front/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx_front/default.conf /etc/nginx/sites-available/default
COPY ./nginx_front/libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_focal_amd64.deb /root/libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_focal_amd64.deb

#RUN add-apt-repository --yes ppa:linuxuprising/libpng12 -y && apt update
RUN dpkg -i ~/libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_focal_amd64.deb
#RUN apt update && apt install libpng12-0 -y

RUN curl -sL https://deb.nodesource.com/setup_14.x |  bash - && apt install -y nodejs
#RUN apt install -y nodejs
RUN node -v

RUN npm install --global yarn

COPY . /var/www/html/cac_rn_frontend/

RUN export NODE_OPTIONS="--max-old-space-size=8192"

RUN cd /var/www/html/cac_rn_frontend && yarn install
RUN cd /var/www/html/cac_rn_frontend && yarn build

FROM base AS prod

COPY --from=build /var/www/html/cac_rn_frontend/build/ /var/www/html/cac_rn_frontend/build/
COPY --from=build /var/www/html/cac_rn_frontend/env.js /var/www/html/cac_rn_frontend/build/
RUN apt update
RUN apt install nginx wget curl iputils-ping nano -y

COPY ./nginx_front/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx_front/default.conf /etc/nginx/sites-available/default
